version: '3'

volumes:
  pg_data:
  bundle:
  node_modules:
  rails_cache:
  assets:

services:
  web:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid && foreman start"
    image: rails_starter/app
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules
      - assets:/app/public/assets
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - db
      - mailhog

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  # mailcatcher:
  #   image: schickling/mailcatcher
  #   ports:
  #     - 1080:1080

